# Generated by Django 4.1.7 on 2023-03-31 11:40

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=core.models.attachment_upload_path),
        ),
        migrations.AlterField(
            model_name='effect',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=core.models.effect_upload_path),
        ),
    ]
