# Generated by Django 4.1.7 on 2023-04-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_person_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
